/* eslint-disable no-console */
/* eslint-disable @typescript-eslint/no-var-requires */
// Generate telemetry-worker/src/locales.generated.ts from src/locales/*.json
// Usage: node scripts/gen-locales.cjs

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const LOCALES_DIR = path.join(ROOT, 'src', 'locales');
const OUT_FILE = path.join(ROOT, 'src', 'locales.generated.ts');

function isValidLangCode(code) {
  return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(code);
}

function toIdent(code) {
  return `locale_${code.replace(/[^a-z0-9]/g, '_')}`;
}

function readLocaleCodes() {
  const files = fs.readdirSync(LOCALES_DIR, { withFileTypes: true })
    .filter(d => d.isFile() && d.name.endsWith('.json'))
    .map(d => d.name);

  const codes = files.map(f => path.basename(f, '.json').toLowerCase());
  for (const code of codes) {
    if (!isValidLangCode(code)) {
      throw new Error(`Invalid locale code from filename: ${code}.json`);
    }
  }
  if (!codes.includes('en')) {
    throw new Error('Missing required locale: en.json');
  }

  // Deterministic order: en first, then the rest sorted.
  const rest = codes.filter(c => c !== 'en').sort((a, b) => a.localeCompare(b));
  return ['en', ...rest];
}

function buildOutput(codes) {
  const imports = codes.map(code => {
    const ident = toIdent(code);
    return `import ${ident} from './locales/${code}.json';`;
  }).join('\n');

  const entries = codes.map(code => `  ${JSON.stringify(code)}: ${toIdent(code)},`).join('\n');
  const list = codes.map(code => `  ${JSON.stringify(code)},`).join('\n');

  return [
    '/* This file is auto-generated by scripts/gen-locales.cjs. Do not edit. */',
    '/* eslint-disable */',
    imports,
    '',
    'export const LOCALES = {',
    entries,
    '} as const;',
    '',
    'export type PageLang = keyof typeof LOCALES;',
    '',
    'export const PAGE_LANGS = [',
    list,
    '] as const satisfies readonly PageLang[];',
    '',
  ].join('\n');
}

function main() {
  const codes = readLocaleCodes();
  const out = buildOutput(codes);
  const prev = fs.existsSync(OUT_FILE) ? fs.readFileSync(OUT_FILE, 'utf8') : null;
  if (prev === out) return;
  fs.writeFileSync(OUT_FILE, out, 'utf8');
}

main();

