export type Locale = "en" | "zh" | "ja" | "ko";

const strings: Record<Locale, Record<string, string>> = {
  en: {
    app_name: "JavManager",
    help_title: "Commands",
    help_search: "search <javId>   Search and download",
    help_local: "local <query>    Search local files",
    help_remote: "remote <javId>   Search JavDB only",
    help_cache: "cache            Show cache stats",
    help_downloads: "downloads        List torrents",
    help_downloading: "downloading      List active downloads",
    help_health: "health           Check service health",
    help_lang: "lang <en|zh|ja|ko> Switch language",
    help_version: "version          Show version",
    help_help: "help             Show help",
    help_quit: "quit             Exit interactive mode",
    help_config: "cfg show|set     View or change config (session)",
    help_test_curl: "--test-curl       JavDB curl-impersonate diagnostic",
    prompt_input: "Input command or JAV ID",
    invalid_jav_id: "Invalid JAV ID: {0}",
    searching: "Searching: {0}",
    no_search_results: "No search results",
    no_torrents_found: "No torrents found",
    local_files_found: "Local files found",
    download_added: "Download task added",
    download_failed: "Failed to add to downloader, magnet link:",
    downloader_unavailable: "Downloader unavailable, magnet link:",
    cache_disabled: "Cache is disabled",
    cache_stats: "Cache: {0} items, {1} torrents, {2} bytes",
    health_ok: "OK",
    health_fail: "Failed",
    gui_title: "JavManager",
    gui_nav_search: "Search",
    gui_nav_downloads: "Downloads",
    gui_nav_settings: "Settings",
    gui_nav_repo: "Repo",
    gui_nav_cloudflare: "Cloudflare",
    gui_section_local_files: "Local Files",
    gui_section_torrents: "Torrents",
    gui_search_button: "Search",
    gui_download_button: "Download",
    gui_status_ready: "Ready",
    gui_status_searching: "Searching...",
    gui_status_download_added: "Download task added",
    gui_status_download_failed: "Download failed",
    gui_settings_save: "Save Settings",
    gui_settings_saved: "Settings saved",
    gui_label_jav_id: "JAV ID",
    gui_placeholder_jav_id: "e.g. ABC-123",
    gui_label_search_local: "Local",
    gui_label_search_remote: "Remote",
    gui_table_title: "Title",
    gui_table_size: "Size",
    gui_table_name: "Name",
    gui_table_state: "State",
    gui_settings_section_everything: "Everything",
    gui_settings_section_qbittorrent: "qBittorrent",
    gui_settings_section_javdb: "JavDB",
    gui_settings_section_download: "Download",
    gui_settings_section_language: "Language",
    gui_field_base_url: "Base URL",
    gui_field_username: "User Name",
    gui_field_password: "Password",
    gui_field_mirror_urls: "Mirror URLs (comma)",
    gui_field_default_save_path: "Default Save Path",
    gui_field_default_category: "Default Category",
    gui_field_default_tags: "Default Tags",
    gui_error_qb_not_configured: "qBittorrent is not configured. Set qBittorrent Base URL in {0}.",
    gui_error_everything_not_configured: "Everything is not configured. Set Everything Base URL in {0}.",
    config_updated: "Config updated",
    usage_config: "Usage: cfg show | cfg set [service] [key] [value] | cfg <service> <key> <value>",
  },
  zh: {
    app_name: "JavManager",
    help_title: "命令",
    help_search: "search <番号>   搜索并下载",
    help_local: "local <关键字>  本地文件搜索",
    help_remote: "remote <番号>   仅远端搜索",
    help_cache: "cache           缓存统计",
    help_downloads: "downloads       下载列表",
    help_downloading: "downloading     下载中列表",
    help_health: "health          健康检查",
    help_lang: "lang <en|zh>    切换语言",
    help_version: "version         版本信息",
    help_help: "help            帮助",
    help_quit: "quit            退出交互",
    prompt_input: "输入命令或番号",
    invalid_jav_id: "番号格式无效: {0}",
    searching: "正在搜索: {0}",
    no_search_results: "无搜索结果",
    no_torrents_found: "未找到种子",
    local_files_found: "发现本地文件",
    download_added: "已添加下载任务",
    download_failed: "加入下载器失败，磁力链接：",
    downloader_unavailable: "下载器不可用，磁力链接：",
    cache_disabled: "缓存已禁用",
    cache_stats: "缓存：{0} 条，{1} 个种子，{2} 字节",
    health_ok: "正常",
    health_fail: "异常",
    gui_title: "JavManager",
    gui_nav_search: "搜索",
    gui_nav_downloads: "下载",
    gui_nav_settings: "设置",
    gui_nav_repo: "代码仓库",
    gui_nav_cloudflare: "社区",
    gui_section_local_files: "本地文件",
    gui_section_torrents: "种子",
    gui_search_button: "搜索",
    gui_download_button: "下载",
    gui_status_ready: "就绪",
    gui_status_searching: "正在搜索...",
    gui_status_download_added: "已添加下载任务",
    gui_status_download_failed: "下载失败",
    gui_settings_save: "保存设置",
    gui_settings_saved: "设置已保存",
    gui_label_jav_id: "番号",
    gui_placeholder_jav_id: "如 ABC-123",
    gui_label_search_local: "本地",
    gui_label_search_remote: "远端",
    gui_table_title: "标题",
    gui_table_size: "大小",
    gui_table_name: "名称",
    gui_table_state: "状态",
    gui_settings_section_everything: "Everything",
    gui_settings_section_qbittorrent: "qBittorrent",
    gui_settings_section_javdb: "JavDB",
    gui_settings_section_download: "下载",
    gui_settings_section_language: "语言",
    gui_field_base_url: "基础 URL",
    gui_field_username: "用户名",
    gui_field_password: "密码",
    gui_field_mirror_urls: "镜像地址（逗号分隔）",
    gui_field_default_save_path: "默认保存路径",
    gui_field_default_category: "默认分类",
    gui_field_default_tags: "默认标签",
    gui_error_qb_not_configured: "qBittorrent 未配置。请在 {0} 中设置 qBittorrent Base URL。",
    gui_error_everything_not_configured: "Everything 未配置。请在 {0} 中设置 Everything Base URL。",
    usage_config: "用法: cfg show | cfg set [service] [key] [value] | cfg <service> <key> <value>",
  },
  ja: {
    app_name: "JavManager",
    help_title: "コマンド",
    help_search: "search <javId>   検索してダウンロード",
    help_local: "local <query>    Everythingでローカル検索",
    help_remote: "remote <javId>   JavDBのみ検索",
    help_cache: "cache            キャッシュ統計",
    help_downloads: "downloads        トレント一覧",
    help_downloading: "downloading      ダウンロード中のみ",
    help_health: "health           ヘルスチェック",
    help_lang: "lang <en|zh|ja|ko> 言語切替",
    help_version: "version          バージョン",
    help_help: "help             ヘルプ",
    help_quit: "quit             終了",
    help_config: "cfg show|set     設定の表示/変更",
    help_test_curl: "--test-curl       curl-impersonate 診断",
    prompt_input: "コマンドまたは品番を入力",
    invalid_jav_id: "無効な品番: {0}",
    searching: "検索中: {0}",
    no_search_results: "結果がありません",
    no_torrents_found: "トレントが見つかりません",
    local_files_found: "ローカルファイルが見つかりました",
    download_added: "ダウンロードを追加しました",
    download_failed: "ダウンローダーに追加できませんでした。マグネットリンク:",
    downloader_unavailable: "ダウンローダーが利用できません。マグネットリンク:",
    cache_disabled: "キャッシュは無効です",
    cache_stats: "キャッシュ: {0} 件, {1} トレント, {2} バイト",
    health_ok: "OK",
    health_fail: "失敗",
    gui_title: "JavManager",
    gui_nav_search: "検索",
    gui_nav_downloads: "ダウンロード",
    gui_nav_settings: "設定",
    gui_section_local_files: "ローカルファイル",
    gui_section_torrents: "トレント",
    gui_search_button: "検索",
    gui_download_button: "ダウンロード",
    gui_status_ready: "準備完了",
    gui_status_searching: "検索中...",
    gui_status_download_added: "ダウンロードを追加しました",
    gui_status_download_failed: "ダウンロード失敗",
    gui_settings_save: "設定を保存",
    gui_settings_saved: "設定を保存しました",
    gui_label_jav_id: "品番",
    gui_placeholder_jav_id: "例: ABC-123",
    gui_label_search_local: "ローカル検索",
    gui_label_search_remote: "リモート検索",
    gui_table_title: "タイトル",
    gui_table_size: "サイズ",
    gui_table_name: "名前",
    gui_table_state: "状態",
    gui_settings_section_everything: "Everything",
    gui_settings_section_qbittorrent: "qBittorrent",
    gui_settings_section_javdb: "JavDB",
    gui_settings_section_download: "ダウンロード",
    gui_settings_section_language: "言語",
    gui_field_base_url: "ベースURL",
    gui_field_username: "ユーザー名",
    gui_field_password: "パスワード",
    gui_field_mirror_urls: "ミラーURL（カンマ区切り）",
    gui_field_default_save_path: "既定の保存先",
    gui_field_default_category: "既定のカテゴリ",
    gui_field_default_tags: "既定のタグ",
    gui_error_qb_not_configured: "qBittorrent が未設定です。{0} で Base URL を設定してください。",
    config_updated: "設定を更新しました",
    usage_config: "使い方: cfg show | cfg set [service] [key] [value] | cfg <service> <key> <value>",
  },
  ko: {
    app_name: "JavManager",
    help_title: "명령",
    help_search: "search <javId>   검색 및 다운로드",
    help_local: "local <query>    Everything 로컬 검색",
    help_remote: "remote <javId>   JavDB만 검색",
    help_cache: "cache            캐시 통계",
    help_downloads: "downloads        토렌트 목록",
    help_downloading: "downloading      다운로드 중만",
    help_health: "health           상태 확인",
    help_lang: "lang <en|zh|ja|ko> 언어 변경",
    help_version: "version          버전",
    help_help: "help             도움말",
    help_quit: "quit             종료",
    help_config: "cfg show|set     설정 보기/변경",
    help_test_curl: "--test-curl       curl-impersonate 진단",
    prompt_input: "명령 또는 품번 입력",
    invalid_jav_id: "유효하지 않은 품번: {0}",
    searching: "검색 중: {0}",
    no_search_results: "검색 결과 없음",
    no_torrents_found: "토렌트를 찾지 못했습니다",
    local_files_found: "로컬 파일 발견",
    download_added: "다운로드 작업이 추가되었습니다",
    download_failed: "다운로더 추가 실패, 마그넷 링크:",
    downloader_unavailable: "다운로더를 사용할 수 없음, 마그넷 링크:",
    cache_disabled: "캐시가 비활성화되었습니다",
    cache_stats: "캐시: {0}개, {1} 토렌트, {2} 바이트",
    health_ok: "정상",
    health_fail: "실패",
    gui_title: "JavManager",
    gui_nav_search: "검색",
    gui_nav_downloads: "다운로드",
    gui_nav_settings: "설정",
    gui_section_local_files: "로컬 파일",
    gui_section_torrents: "토렌트",
    gui_search_button: "검색",
    gui_download_button: "다운로드",
    gui_status_ready: "준비됨",
    gui_status_searching: "검색 중...",
    gui_status_download_added: "다운로드 작업이 추가되었습니다",
    gui_status_download_failed: "다운로드 실패",
    gui_settings_save: "설정 저장",
    gui_settings_saved: "설정이 저장되었습니다",
    gui_label_jav_id: "품번",
    gui_placeholder_jav_id: "예: ABC-123",
    gui_label_search_local: "로컬 검색",
    gui_label_search_remote: "원격 검색",
    gui_table_title: "제목",
    gui_table_size: "크기",
    gui_table_name: "이름",
    gui_table_state: "상태",
    gui_settings_section_everything: "Everything",
    gui_settings_section_qbittorrent: "qBittorrent",
    gui_settings_section_javdb: "JavDB",
    gui_settings_section_download: "다운로드",
    gui_settings_section_language: "언어",
    gui_field_base_url: "기본 URL",
    gui_field_username: "사용자 이름",
    gui_field_password: "비밀번호",
    gui_field_mirror_urls: "미러 URL(쉼표 구분)",
    gui_field_default_save_path: "기본 저장 경로",
    gui_field_default_category: "기본 카테고리",
    gui_field_default_tags: "기본 태그",
    gui_error_qb_not_configured: "qBittorrent가 설정되지 않았습니다. {0}에서 Base URL을 설정하세요.",
    config_updated: "설정이 업데이트되었습니다",
    usage_config: "사용법: cfg show | cfg set [service] [key] [value] | cfg <service> <key> <value>",
  },
};

export class LocalizationService {
  private locale: Locale;

  constructor(locale: Locale) {
    this.locale = locale;
  }

  get currentLocale(): Locale {
    return this.locale;
  }

  setLanguage(locale: Locale): void {
    this.locale = locale;
  }

  get(key: string): string {
    return strings[this.locale][key] ?? strings.en[key] ?? key;
  }

  getFormat(key: string, ...args: Array<string | number>): string {
    const template = this.get(key);
    return args.reduce<string>(
      (acc, value, index) => acc.replace(`{${index}}`, String(value)),
      template
    );
  }
}
