/* This file is auto-generated by scripts/gen-locales.cjs. Do not edit. */
/* eslint-disable */
import locale_en from './locales/en.json';
import locale_fil from './locales/fil.json';
import locale_id from './locales/id.json';
import locale_ja from './locales/ja.json';
import locale_ko from './locales/ko.json';
import locale_ms from './locales/ms.json';
import locale_th from './locales/th.json';
import locale_vi from './locales/vi.json';
import locale_zh from './locales/zh.json';

export const LOCALES = {
  "en": locale_en,
  "fil": locale_fil,
  "id": locale_id,
  "ja": locale_ja,
  "ko": locale_ko,
  "ms": locale_ms,
  "th": locale_th,
  "vi": locale_vi,
  "zh": locale_zh,
} as const;

export type PageLang = keyof typeof LOCALES;

export const PAGE_LANGS = [
  "en",
  "fil",
  "id",
  "ja",
  "ko",
  "ms",
  "th",
  "vi",
  "zh",
] as const satisfies readonly PageLang[];
